name: Build Flet App to APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet flet-core flet-pyodide buildozer

      - name: Install Buildozer and Android SDK
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/package.domain/package.yourapp/' buildozer.spec
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet_app_apk
          path: bin/*.apk
